---
- hosts: localhost
  connection: local
  gather_facts: False
  vars_files:
  - vars.yml
  tasks:

    - name: provision
      ec2:
         aws_access_key: "{{ec2_access_key}}"
         aws_secret_key: "{{ec2_secret_key}}"
         region: "us-west-2"
         instance_type: t2.micro
         image: "ami-4836a428"
         key_name: chinni505
         group_id: sg-c58b02be
         vpc_subnet_id: subnet-83d969e4
         count: 1
         wait: true
         instance_tags:
            testing: ansible-test

      register: ec2
    - name: Add instance public IP to hostgroup
      add_host: hostname="{{ item.public_ip }}" groups=ec2hosts
      with_items: "{{ ec2.instances }}"
    - name: waiting here 
      wait_for: host={{item.public_ip}} port=22 delay=60 timeout=320 state=started
      with_items: "{{ec2.instances}}"
- hosts: ec2hosts
  name: ec2hosts list
  user: ec2-user
  become: true
  gather_facts: true
  tasks:
    - name: copy python script file
      template: src=pyth.py.j2 dest=/tmp/pyth.py
    - cron:
        name: "cron job"
        minute: "0"
        hour: "0"
        job: "/usr/bin/python /tmp/s3.py"
